name: Release
on:
  push:
    branches:
      - main
jobs:
  update-specs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      git_ref: ${{ steps.commit.outputs.git_ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "$(date)" > build_date.txt
      - name: GIT commit and push changes
        run: |
          git config user.name "username"
          git config user.email "mail@example.com"
          git add .
          git commit -m "Commit time" || echo "No changes to commit"
          git push
      - name: Set git_ref
        id: commit
        run: echo "git_ref=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
  tag:
    name: Create Release Tag
    runs-on: ubuntu-latest
    needs: update-specs
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.bump_version.outputs.new_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ needs.update-specs.outputs.git_ref }}
      - name: Bump Minor Version
        id: bump_version
        run: |
          #!/bin/bash
          set -euo pipefail
          
          fetch_all_git_tags() {
            git fetch --tags
          }
          
          get_latest_release_tag() {
            git tag --sort=-v:refname | ( grep --extended-regexp 'release/[0-9]+\.[0-9]+\.[0-9]+$' || [ $? = 1 ] ) | head --lines 1 | sed 's/release\///'
          }
          
          calculate_new_minor_version() {
            local latest=$1
            local latest=${latest:-0.0.0}
            local major=$(echo $latest | cut -d . -f 1)
            local minor=$(echo $latest | cut -d . -f 2)
            echo "$major.$((minor+1)).0"
          }
          
          create_and_push_new_tag() {
            local new_version=$1
            local new_tag="release/$new_version"
            git tag $new_tag
            git push origin $new_tag
            echo "new_version=$new_version" >> "$GITHUB_OUTPUT"
          }
          
          fetch_all_git_tags
          latest=$(get_latest_release_tag)
          new_version=$(calculate_new_minor_version "$latest")
          create_and_push_new_tag "$new_version"
  print-build-date:
    name: Print Build Date
    runs-on: ubuntu-latest
    needs: [update-specs, tag]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ needs.update-specs.outputs.git_ref }}
      - name: Print build_date.txt
        run: cat build_date.txt
      - name: Print git tag
        run: git describe --tags --abbrev=0
    